### ISSUE TITLE
isaac / 9.30. 일일과제 

### ISSUE THREAD

**Issue by hwisaac** [fastcampus-team4/Aesop#11]
# 뭘 써야 돼요?

**Comment by Hyeeeein** [comment]
볼드체로 당당하게 말씀하셔서 당황했네요..
다른 분들 것 보고 그거 토대로 작성하시면 됩니다

**Comment by hyerimhan** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
