### ISSUE TITLE
제안) 리포지토리 권한 요청

### ISSUE THREAD

**Issue by hwisaac** [fastcampus-team4/Aesop#39]
저희 조원 모두에게 관리자 권한을 부여해주세요
참고: [모든 브랜치가 있는 Git 리포지토리 복제 (링크)](https://hengbokhan.tistory.com/140)

**Comment by Hyeeeein** [comment]
setting 탭에 manage access 라는 탭이 없어서 좀 더 찾아봐야 할 것 같아요 조금만 기다려주세요
